# Auto-generated by scripts/generate_init_stub.py -- do not edit.
#
# Flattened re-export of easybuild/easyblocks/s/swig.py so that LSPs
# resolve `from easybuild.easyblocks.swig import ...` without executing the
# pkgutil.extend_path logic in __init__.py.
#
# Part of EasyBuild -- https://github.com/easybuilders/easybuild
# Copyright 2026 Ghent University (GPLv2 / MIT / BSD-3-clause)
from .s.swig import *  # noqa: F401,F403
