# Auto-generated by scripts/generate_init_stub.py -- do not edit.
#
# Flattened re-export of easybuild/easyblocks/x/xml.py so that LSPs
# resolve `from easybuild.easyblocks.xml import ...` without executing the
# pkgutil.extend_path logic in __init__.py.
#
# Part of EasyBuild -- https://github.com/easybuilders/easybuild
# Copyright 2026 Ghent University (GPLv2 / MIT / BSD-3-clause)
from .x.xml import *  # noqa: F401,F403
