#!/usr/bin/env python3
##
# Copyright 2026 Ghent University
#
# This file is triple-licensed under GPLv2 (see below), MIT, and
# BSD three-clause licenses.
#
# This file is part of EasyBuild,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# the Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI)
# (http://www.ewi-vlaanderen.be/en).
#
# https://github.com/easybuilders/easybuild
#
# EasyBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation v2.
#
# EasyBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EasyBuild.  If not, see <http://www.gnu.org/licenses/>.
##
"""
Generate PEP 561 stubs for easybuild.easyblocks so that LSPs and type-checkers
resolve flattened imports like `from easybuild.easyblocks.clang import
DEFAULT_TARGETS_MAP` even though the physical file lives at
easybuild/easyblocks/c/clang.py.

The runtime mapping is performed by pkgutil.extend_path in
easybuild/easyblocks/__init__.py, which LSPs do not execute. A single
__init__.pyi re-export is NOT sufficient because LSPs resolve
`from easybuild.easyblocks.clang import X` as a module-path import (they look
for a file clang.py / clang.pyi), not as an attribute access on the package.
So for each easyblock a per-module <name>.pyi stub is generated that re-exports
everything from .<subdir>.<name>.

Modules whose name collides with their subdirectory (e.g. r/r.py) are skipped:
those are already handled by the subdirectory's own __init__.py re-export, and a
<name>.pyi would be shadowed by the <name>/ subdirectory anyway.

Usage:
    python scripts/generate_init_stub.py          # write all stubs
    python scripts/generate_init_stub.py --check  # exit 1 if any stub is out of sync
"""
import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EASYBLOCKS_DIR = REPO_ROOT / "easybuild" / "easyblocks"

MODULE_HEADER_TEMPLATE = """# Auto-generated by scripts/generate_init_stub.py -- do not edit.
#
# Flattened re-export of easybuild/easyblocks/{subdir}/{name}.py so that LSPs
# resolve `from easybuild.easyblocks.{name} import ...` without executing the
# pkgutil.extend_path logic in __init__.py.
#
# Part of EasyBuild -- https://github.com/easybuilders/easybuild
# Copyright 2026 Ghent University (GPLv2 / MIT / BSD-3-clause)
"""


def discover_modules():
    """Return a sorted list of (subdir, module_name) tuples for every easyblock.

    Modules whose name equals their subdirectory (e.g. r/r.py) are skipped: the
    subdirectory __init__.py already re-exports them, and a <name>.pyi stub
    would be shadowed by the <name>/ subdirectory.
    """
    found = []
    # Subdirectories that map to flattened module names.  and
    # is intentionally excluded.

    for sub_path in EASYBLOCKS_DIR.iterdir():
        if not sub_path.is_dir():
            continue
        # 'generic' is a real subpackage (its modules are imported via easybuild.easyblocks.generic.X)
        if sub_path.name == 'generic':
            continue
        for py_file in sorted(sub_path.glob("*.py")):
            if py_file.name == "__init__.py":
                continue
            name = py_file.stem
            if name == sub_path.name:
                continue
            found.append((sub_path.name, name))
    found.sort()
    return found


def render_module_stub(subdir, name):
    """Render a per-module <name>.pyi re-export stub."""
    header = MODULE_HEADER_TEMPLATE.format(subdir=subdir, name=name)
    return header + "from .%s.%s import *  # noqa: F401,F403\n" % (subdir, name)


def render_all_stubs(modules):
    """Return {Path: content} for every stub file the generator should produce."""
    files = {}
    for subdir, name in modules:
        path = EASYBLOCKS_DIR / ("%s.pyi" % name)
        files[path] = render_module_stub(subdir, name)
    return files


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate PEP 561 stubs for easybuild.easyblocks.",
    )
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if any stub is out of sync")
    args = parser.parse_args(argv)

    all_stubs = render_all_stubs(discover_modules())

    if args.check:
        problems = []
        for path, content in sorted(all_stubs.items()):
            rel = path.relative_to(REPO_ROOT)
            if not path.exists():
                problems.append("missing: %s" % rel)
            elif path.read_text(encoding="utf-8") != content:
                problems.append("out of date: %s" % rel)
        expected_paths = set(all_stubs)
        for existing in sorted(EASYBLOCKS_DIR.glob("*.pyi")):
            if existing not in expected_paths:
                problems.append("stale: %s" % existing.relative_to(REPO_ROOT))
        if problems:
            sys.stderr.write("Stub files are out of sync:\n")
            for line in problems:
                sys.stderr.write("  %s\n" % line)
            sys.stderr.write("Run `python scripts/generate_init_stub.py` to fix.\n")
            return 1
        sys.stdout.write("All %d stub files are up to date.\n" % len(all_stubs))
        return 0

    # Write mode: remove stale stubs, then write all expected files.
    expected_paths = set(all_stubs)
    for existing in EASYBLOCKS_DIR.glob("*.pyi"):
        if existing not in expected_paths:
            existing.unlink()
    for path, content in sorted(all_stubs.items()):
        path.write_text(content, encoding="utf-8")
    sys.stdout.write("Wrote %d stub files\n" % len(all_stubs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
