name: Black Formatter
on: [push, pull_request]
jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Black Code Formatter Diff
        uses: lgeiger/black-action@master
        # Use diff to see recommended changes and check to return error code
        with:
          args: "--diff --check ."
